### ISSUE TITLE
Default update interval

### ISSUE THREAD

**Issue by ntompson** [CJNE/ha-myenergi#46]
Hi,

Loving the work you've done here - so useful to be able to integrate my new Zappi / hub just by pointing at your repo! One question: I note that the default update interval is 60 seconds. Is this the minimum value that I should use? Is it related to the refresh rate of the Zappi / hub to the cloud? Or is it in respect of API rate limiting as requested by MyEnergi?

It would be nice to have the sensors update a bit more frequently, but I wanted to check whether it was a good / bad idea first.

Might be worth a mention in the readme.

Thanks,

Nick

**Comment by G6EJD** [comment]
If you observe your ME LED’s you’ll see they use a 1-sec update rate, so you can’t go any faster than that. You could slow the rate down though.

**Comment by CJNE** [comment]
Thanks Nick!

The default 60 second update interval was based on what DrChris thought was reasonable in some forum thread over at their forum. It is possible to change in the integration options if you want.

Good idea to have this info in the readme, will add 👍🏻


Skickat från min iPhone

**Comment by ntompson** [comment]
Thanks for the note @CJNE. If 60s is what is considered reasonable, I'm more than happy to stay with that.

@G6EJD: 1 second updating sounds surprisingly rapid. Are you saying the hub is hitting the API every second with measurement updates? It would be great to have that kind of resolution in the measurement data, but I can also see how 1 s API hits from HomeAssistant might be considered unreasonable by MyEnergi.

If Zappi is sending measurements to the hub every second, wouldn't it be great if MyEnergi developed / supported a local API to avoid having to hit the cloud? Have they ever made any comments for or against the idea?

**Comment by G6EJD** [comment]
@ntompson : The Harvi sends data to the Hub every 1-sec, so that must be the fastest update rate possible. MyEnergi did indeed say no faster than 60-secs and providing customers don't abuse the update rate they are content to support it, until that is there are too many people requesting high data rates!
Given data is recorded by the Master device at 1 reading/sec then they need to upload it equally quickly otherwise their devices would very quickly overrun local storage.
I've set my update rate at 6000-secs as I'll still get all the data albeit in one batch and don't see any need to request it any faster as all the data will be visible.
It appears the ME API units are in Watt-sec which is a lot of resolution, presumably chosen for a reason, who knows, I suppose they can always slow the rate down if it becomes unstainable.

**Comment by ntompson** [comment]
Thanks for the note @G6EJD. I hadn't realised that multiple readings could be pulled down at each refresh instance. Having said that, looking at the data I'm seeing, I don't think I'm getting more resolution than one measurement per 60 second interval, but I'm also OK with that.
