### ISSUE TITLE
Grid Voltage taken from Zappi Slave, no Eddi vHub grid voltage

### ISSUE THREAD

**Issue by japaho** [CJNE/ha-myenergi#534]
## Configuration

```yaml
Add your logs here.
```

## Describe the bug

Eddi (as vHub) + Zappi 2 - grid voltage sensor is taken from Zappi - no Eddi voltage sensor.

## Debug log

```text

Add your logs here.

```

**Comment by G6EJD** [comment]
I don’t understand this, it makes no sense. The grid voltage at the Zappi and Eddi measurements are identical and always will be.

**Comment by G6EJD** [comment]
It’s a design choice because if there is a Zappi present, that makes a more logical choice for voltage readings to cater for 3-phase installations.

The Eddi is a single phase device the Zappi can be 1 or 3-phase.

If a Zappi is not fitted then the voltage source comes from the Eddi.

In your case your getting a better voltage reading from the Zappi as it’s not suffering from cable resistance and hence a reduced voltage. 

Whatever the device source, it would be easy to achieve a voltage calibration in HA by adding in an offset, ideally in percentage terms to keep the reduction of voltage aligned for the Eddi. A constant offset would introduce more errors and should be avoided.

**Comment by G6EJD** [comment]
This isn’t an issue for this integration and can never be solved unless MyEnergi make a change - highly unlikely.

This issue needs to be closed by the instigator.

**Comment by G6EJD** [comment]
Only the master returns the voltage readings and you can’t have two masters. If you check the Eddi response you’ll see it returns 0.0volts when it’s not the master.

**Comment by japaho** [comment]
Thanks for your help.

**Comment by japaho** [comment]
.
