### ISSUE TITLE
More frequent updates?

### ISSUE THREAD

**Issue by i00** [CJNE/ha-myenergi#537]
**Is your feature request related to a problem? Please describe.**
Currently the sensors update every 5 mins - is there a reason for this? - is it possible to poll directly from the devices if there are call restrictions on the API calls (would be better IMHO if it was local poling anyway)?

**Describe the solution you'd like**
More frequent updates, pref with local polling

**Describe alternatives you've considered**
Updating source to increase polling period

**Additional context**

**Comment by G6EJD** [comment]
Why would you want to do this when:
1. You run the risk of MyEnergi starting to charge like all other data suppliers for server access rates.
2. Water heating is inherently slow, it would take probably an hour to heat a normal volume of water 
3. An EV would take hours to charge.


These sort of requests are generally made by people who don’t understand system dynamics or engineering., or the implication ms of increasing data rates.

**Comment by LeiChat** [comment]
I'm content with the polling frequency but, it would be awesome if we could access the data locally, rather than via the myenergi API. Perhaps if enough of us up vote a request for local access on their official forums (myenergi.info) MyEnergi will consider implementing the functionality. I agree with @G6EJD's first point. I would hate for MyEnergi to revoke, limit, or start charging for access to the API, which increasing polling frequency of ha-myenergi might increase the risk of happening.

**Comment by trizmark** [comment]
@i00 Currently sensors update every minute. That's the data resolution the API provides and it's unlikely to change. The local devices don't expose an easily readable interface, so you need to be a bit more 'creative'.
There are 2 ways to get more frequent updates:
1) via the local radio comms that goes on between the various ME devices
2) in case of the libbi, spying on the modbus interface

I've got the second option up and running and you get much more detailed info compared to the official API. I did have all the HW for option one as well, however not all the info is presented on the radio interface.

**Comment by CJNE** [comment]
Closing this, local access would be nice but out of scope for this integration :)
