### ISSUE TITLE
Export / Import / Generated today sensors completely different from app/reality

### ISSUE THREAD

**Issue by DReffects** [CJNE/ha-myenergi#555]
## Version of the custom_component
0.0.27

## Configuration
nothing related to the intergration

## Describe the bug
My values for Generated Today, Export Today and Import Today are completely different from reality and what the app is reporting. 
Generated Today in the HA Integration: 54,57 kWh
Generated Today in the MyEnergi App/Website: 70,7 kWh
Generatated Today from the Inverter Status: 71,0 kWh

This seems to have started in March '24. 
The Deviation in march is -16%, April onwards its exactly 23%. 

## Debug log
I am unsure what logs to provide here. The Integration works but values are wrong. What kind of Logs should I enable?

**Comment by G6EJD** [comment]
Are you confusing the time integration being used by the MyEnergi App and this integration, they are different, this is most likely a quantisation error whereby the MyEnergi App uses the all the data recorded at 1-sec intervals and for practical reasons this integration uses a much wider gap between readings, meaning it will miss modulation of the energy variations, hence you get much lower readings. I see this as a compromise of making too many API calls to the MyEnergi server to get the ideal resolution and correct resul, verses a simple and low rate call that gets data for say every hour. 
The compromise is not overloading and over using what is a free API call service, suppliers like SolarEdge would shut the API down after about 300 calls a day, so MyEnergi are very generous. 

But why do so few users report any discrepancies in their readings, well I have no doubt it’s down to your particular load modulation, by that I mean your load levels are not constant snd highly variable during the day, so tend a sample, then wait, but during that wait your property is consuming high spikes of energy which are missed at the next data point, whereas I think in most properties the load is largely steady/constant most of the time. 

That’s what I see.

**Comment by DReffects** [comment]
Thanks for the feedback. I don't quite know what you mean, unfortunately. The integration worked flawlessly until mid march where the deviations started. 

My refresh Interval is set to 10 seconds atm, but why would this affect cumulating values at all?
The generated_today reading should not be affected by any gaps between readings since it is a total for each day. Why would this value be off at the end of the day, even with fewer API calls?

Or are generated_today, export_today, etc eing calculated within the integration instead of an API call?

Thanks :-)

**Comment by G6EJD** [comment]
A reading used/taken at 10-sec intervals will always produce a lower result (load dependent) than the same result comprised of 1-sec intervals. We know the MyEnergi system uses all 1-sec readings to accumulate its values as does this integration for some of the readings.
So a set of readings over 20-secs could be:
10 then 10 = 20
Or
10, 11, 12, 13, 14,15, 16, 17,18,19,11,12,13,14,15,16,17,18,19=14.5

So, 14.5 verses 10 that’s the quantisation difference as an example.

Yes, the only actual readings are Grid and Solar if in the latter case you have a Solar CT fitted, all the rest are derived values. 

So it’s possible your particular installation of CT’s is in fact incorrect, whereby the CT’s for probably solar are not reading correctly or are on the wrong cable, or just as likely that your property has a particularly low power factor which means your readings will always be out. So that means the vector sum of currents can be measured at say 10A, but depending on the PF the real element of the 10A current is 0.8 lower then that measured which is in fact a typical PF for many inductive loads like fans or compressors, so what sort of loads do you have in your property, any ASHP’s?

**Comment by DReffects** [comment]
Thanks for the explanation.
I do have ct clamps installed plus an extra harvi.

I was just wondering why the myenergi app is reporting next to perfect values. I was under the impression, that the API would provide the totals like generated today, export today etc.

 It's typical household mix. A couple of computers, the occasional EV charge, lights, household appliances. 

I wonder what changed in March. Previously I had a constant 3% deviation compared to what a Shelly 3em, the myenergi app and the inverter itself was reporting. The it jumped to 23%.

Is there some sort of test I can run to narrow this down?

If my CT clamps would be installed incorrectly, all my readings in the myenergi app would be off too I guess.

**Comment by DReffects** [comment]
I've changed the polling Interval from 6 seconds (previously set) to 1 second at midnight yesterday. 

Now deviations are way worse:
Integration reports 12,56 kWh
Inverter reports 19,72 kWh
myenergi Website reports 19,66 kWh

Thats a 36% difference.

**Comment by G6EJD** [comment]
Then your experimentation can reveal what’s going on. Clearly it is quantisation errors.
I would set the rate at 1-sec (already done) then move it to 10-secs an order of magnitude greater and then you can more easily examine the relationship between the results. 

its clear all the data packets are arriving at the MyEnergi server as the top-level results are near identical, so this leaves the polling interval set on your HA integration, but assuming default settings, snd noting no-one seems to have an issue then it seems logical to conclude that your integration settings or overall installation is corrupted in some way. 

It’s got to be worth deleting snd reinstalling the MyEnergi integration to start from a clean place.

**Comment by heikone** [comment]
Just a contribution from my side.
I'm using a solar system from RCT Power and a Myenergi Zappi.
The systems act independent from each other, but a are equipped with clamps to measure the power flows by both services.
Anyway, at least one of the power flows, respectively the energy amounts, is directly available in both systems without any calculations or integration on my side (or by Homeassistant system).
This is the energy exported to the grid.

Here ist the comparison of RCT and Myenergi measurements:

This month (July 2024):
RCT: 992 kWh vs. Myenergi: 916 kWh --> Diff. -8%

Today (July, 31., 2024):
RCT: 10.2 kWh vs. Myenergi: 10.5 kWh --> Diff. +3% 

On the one hand, if I look at today's sum, this is a magnitude of energy difference, that I've expected, but the difference for last month's data is significant. 

When I have more time, I will check monthly data for each month of 2024 to see, if the value is changing over the year, as @DReffects reported.

Greetings, Heiko

**Comment by DReffects** [comment]
@heikone Thanks for the input. I'd be very interested in your deviations. 

I've switched to 10 Seconds and deviation returned to 22%. 

Deviations are extreme during the day. Currently I have 48% deviation. Since the generated today values continue to rise when it's dark (for some strange reason) these values are more or less useless. 

What kind of update intervals do you guys use?

**Comment by heikone** [comment]
As proposed, here is my monthly listing from March to July:

March: RCT 283 kWh vs. Myenergi 214 kWh --> -25%
April : RCT 510 kWh vs. Myenergi 476  kWh --> -7%
May: RCT 938 kWh vs. Myenergi 890  kWh --> -5%
June: RCT 958 kWh vs. Myenergi 883  kWh --> -8%
July: RCT 1003 kWh vs. Myenergi 927  kWh --> -8%

March is surprising me, whereas the other months are within my tolerance expectation.
Currently, I'm not at  home and cannot check, what the "official" utility meter in the wall cabinet counted. I believe, this is the most reliable.

Concening your question about the update frequency, @DReffects: I cannot tell you, because the values reported are directly taken from the apps of the devices.

Hope that helps,
Heiko

**Comment by DReffects** [comment]
Thanks for all your input.
Quick update: I've upgraded both hub and zappi to the latest version (still had the "original" FW from 2022 on both devices because 'never touch a running wallbox') and oh boy: the cumulative values are next to perfect now!

myenergi App reports 60,8 kWh
Home Assistant reports  60,1 kWh (10 seconds refresh rate set)
Inverter reports 60,59 kWh

Also, the solar generation reportings that continued despite being dark already have stopped. 
Now this is awesome!

Do you guys have any idea though why this is happening? I don't get how the app was correct before the upgrade and the API "broken". 

:-D

**Comment by G6EJD** [comment]
No idea, I just assumed your equipment was up-to-date for firmware, and c5 was a significant update so I’m surprised it ever worked.
Good to hear it’s resolved now.

**Comment by G6EJD** [comment]
The issue can be closed now!

**Comment by CJNE** [comment]
Thanks :)
