### ISSUE TITLE
Missing myenergi in integrations

### ISSUE THREAD

**Issue by scannie67** [CJNE/ha-myenergi#69]
The installation in HACS was successful.
But the next step failed.

Myenergi can't be find in (=) integrations.
Do I something wrong?

**Comment by hw-hirsch** [comment]
Same problems here

**Comment by G6EJD** [comment]
Did you restart the HA host?

**Comment by CJNE** [comment]
Home Assistant has changed the UI somewhat in the latest versions, so that might confuse things.
After installing the integration using HACS you need to restart Home Assistant.
After that, go to Configuration (not HACS) the to "Devices and services" and click "Add integration" att the bottom right of the screen.

**Comment by scannie67** [comment]
For me it worked one day later….

**Comment by CJNE** [comment]
Closing this, feel free to open if problem persists

**Comment by gdotp01** [comment]
Its strange but i've run across this as well. HACs installed and downloaded the myenergi plugin but when i try adding it to integrations its not there. I have restarted HA, a few times 
It think its now added under settings-->Devices & Services-->Add Integration

**Comment by G6EJD** [comment]
I’ve just built another HA platform and added the MyEnergi integration, it all worked perfectly. Hub Serial and API key, all the entities appear as expected. Depending on how many ME devices you have there should be typically 3 or 4 devices. For me 4 because I have Harvi, HUB, Zappi and Eddi, with all the entities listed too.

**Comment by gdotp01** [comment]
is there any way i can check if it installed by looking for the files.? Its showing as an integration in HACs but not shwoiujng when I then try to add this so I'm not sure what is wrong.

**Comment by gdotp01** [comment]
Oh oh Hold up. It seems to have appeared. I've not changed anything. Its a bit like the report above...seems to take time to appear
